<a href="https://colab.research.google.com/github/karandeep1729/Data-Analysis-and-Statistics/blob/main/Inferential_Stats_HandsON.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
data = pd.read_csv('/content/purchase_data (1) (1).csv')
data

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00069042,F,0-17,10.0,A,2,0.0,3.0,NaN,NaN,8370.0
1,1000001,P00248942,F,0-17,10.0,A,2,0.0,1.0,6.0,14.0,15200.0
2,1000001,P00087842,F,0-17,10.0,A,2,0.0,12.0,NaN,NaN,1422.0
3,1000001,P00085442,F,0-17,10.0,A,2,0.0,12.0,14.0,NaN,1057.0
4,1000002,P00285442,M,55+,16.0,C,4+,0.0,8.0,NaN,NaN,7969.0
...,...,...,...,...,...,...,...,...,...,...,...,...
263010,1004473,P00041942,M,36-45,1.0,B,3,0.0,5.0,18.0,NaN,3722.0
263011,1004473,P00115142,M,36-45,1.0,B,3,0.0,1.0,8.0,17.0,19253.0
263012,1004473,P00188442,M,36-45,1.0,B,3,0.0,5.0,7.0,NaN,3608.0
263013,1004473,P00119442,M,36-45,1.0,B,3,0.0,5.0,NaN,NaN,3604.0
263014,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 263015 entries, 0 to 263014
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   User_ID                     263015 non-null  int64
 1   Product_ID                  263014 non-null  object
 2   Gender                      263014 non-null  object
 3   Age                         263014 non-null  object
 4   Occupation                  263014 non-null  float64
 5   City_Category               263014 non-null  object
 6   Stay_In_Current_City_Years  263014 non-null  object
 7   Marital_Status              263014 non-null  float64
 8   Product_Category_1          263014 non-null  float64
 9   Product_Category_2          181501 non-null  float64
 10  Product_Category_3          80582 non-null   float64
 11  Purchase                    263014 non-null  float64
dtypes: float64(6), int64(1), object(5)
memory usage: 24.1+ MB

In [ ]:
#Which function is used to get the basic statistical analysis of our data.
data.describe()

,User_ID,Occupation,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
count,2.630150e+05,263014.000000,263014.000000,263014.000000,181501.000000,80582.000000,263014.000000
mean,1.002941e+06,8.083558,0.408685,5.291099,9.844756,12.658298,9319.305269
std,2.593126e+03,6.524052,0.491592,3.745722,5.086696,4.129156,4970.152966
min,1.000000e+01,0.000000,0.000000,1.000000,2.000000,3.000000,185.000000
25%,1.001457e+06,2.000000,0.000000,1.000000,5.000000,9.000000,5863.000000
50%,1.002972e+06,7.000000,0.000000,5.000000,9.000000,14.000000,8060.000000
75%,1.004335e+06,14.000000,1.000000,8.000000,15.000000,16.000000,12059.000000
max,1.006040e+06,20.000000,1.000000,18.000000,18.000000,18.000000,23961.000000

In [ ]:
data.isnull().sum()

User_ID                            0
Product_ID                         1
Gender                             1
Age                                1
Occupation                         1
City_Category                      1
Stay_In_Current_City_Years         1
Marital_Status                     1
Product_Category_1                 1
Product_Category_2             81514
Product_Category_3            182433
Purchase                           1
dtype: int64

In [ ]:
data.isnull().sum().sum()

263956

In [ ]:
data.shape

(263015, 12)

In [ ]:
data.dropna(inplace=True)

In [ ]:
data.shape

(80582, 12)

In [ ]:
data.isnull().sum()

User_ID                       0
Product_ID                    0
Gender                        0
Age                           0
Occupation                    0
City_Category                 0
Stay_In_Current_City_Years    0
Marital_Status                0
Product_Category_1            0
Product_Category_2            0
Product_Category_3            0
Purchase                      0
dtype: int64

In [ ]:
data.duplicated().sum()

0

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 80582 entries, 1 to 263011
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   User_ID                     80582 non-null  int64
 1   Product_ID                  80582 non-null  object
 2   Gender                      80582 non-null  object
 3   Age                         80582 non-null  object
 4   Occupation                  80582 non-null  float64
 5   City_Category               80582 non-null  object
 6   Stay_In_Current_City_Years  80582 non-null  object
 7   Marital_Status              80582 non-null  float64
 8   Product_Category_1          80582 non-null  float64
 9   Product_Category_2          80582 non-null  float64
 10  Product_Category_3          80582 non-null  float64
 11  Purchase                    80582 non-null  float64
dtypes: float64(6), int64(1), object(5)
memory usage: 8.0+ MB

# Encoding

In [ ]:
# is a method which allows us to convert categorical values into numerical values

In [ ]:
data.dtypes

User_ID                         int64
Product_ID                     object
Gender                         object
Age                            object
Occupation                    float64
City_Category                  object
Stay_In_Current_City_Years     object
Marital_Status                float64
Product_Category_1            float64
Product_Category_2            float64
Product_Category_3            float64
Purchase                      float64
dtype: object

In [ ]:
data['Gender'].nunique()    #nunique fxn gives us the number of unique values in our  column

2

In [ ]:
data['Age'].nunique()

7

In [ ]:
#Find the unique values in these columns -> City_category, age, gender, Stay_In_Current_City_Years
# number of unique values, what are those unique values and then what is the count of those unique values.
# 8:37
data['City_Category'].unique()       #to see the unique values present in your column

array(['A', 'B', 'C'], dtype=object)

In [ ]:
data['Gender'].unique()

array(['F', 'M'], dtype=object)

In [ ]:
data['Age'].unique()

array(['0-17', '46-50', '26-35', '51-55', '36-45', '18-25', '55+'],
      dtype=object)

In [ ]:
data['Product_ID'].unique()

array(['P00248942', 'P00184942', 'P00145042', 'P00231342', 'P0096642',
       'P00036842', 'P00249542', 'P00303442', 'P00078742', 'P00085942',
       'P00182642', 'P00155442', 'P00221342', 'P00111142', 'P0094542',
       'P00148642', 'P00113242', 'P00110842', 'P00182342', 'P00042142',
       'P00244242', 'P00019342', 'P00073842', 'P00190742', 'P00151842',
       'P00112642', 'P00034442', 'P00222242', 'P00118342', 'P00324742',
       'P00190042', 'P00158542', 'P00112542', 'P00127842', 'P00125942',
       'P00058142', 'P00251642', 'P00351142', 'P00262242', 'P00225842',
       'P00278942', 'P00177442', 'P00000642', 'P00288942', 'P00270942',
       'P00345842', 'P00032042', 'P00031842', 'P00206442', 'P00046742',
       'P00289342', 'P00281742', 'P00266642', 'P00026042', 'P00216342',
       'P00102642', 'P00127442', 'P00345642', 'P00115342', 'P00037142',
       'P00192042', 'P00086442', 'P00028442', 'P00277442', 'P00085242',
       'P00142142', 'P00030942', 'P00112142', 'P00273442', 'P00321742',
       'P00051942', 'P00010742', 'P00114942', 'P00030842', 'P00078542',
       'P00324442', 'P00350942', 'P00000142', 'P00034042', 'P00130742',
       'P00024142', 'P00209742', 'P00160042', 'P00016542', 'P00016742',
       'P00227642', 'P00146142', 'P00129842', 'P00243942', 'P00244142',
       'P00190142', 'P00109242', 'P00145942', 'P00148842', 'P00237542',
       'P00171542', 'P00110742', 'P00119142', 'P00151742', 'P0096442',
       'P00182142', 'P00289942', 'P00113142', 'P00165442', 'P00192542',
       'P00198142', 'P00166942', 'P00003442', 'P00137642', 'P00195842',
       'P00064042', 'P00015542', 'P00105142', 'P00054542', 'P00034742',
       'P00053942', 'P00173342', 'P00233342', 'P00234842', 'P00127942',
       'P00161542', 'P0096542', 'P00074142', 'P00223842', 'P00014842',
       'P00274342', 'P00208742', 'P00117042', 'P00141942', 'P00088542',
       'P00035542', 'P00057942', 'P00059442', 'P00154042', 'P00071242',
       'P00050442', 'P0097342', 'P00205442', 'P00087042', 'P00087342',
       'P00035842', 'P00275842', 'P00351342', 'P00079742', 'P00143642',
       'P00127642', 'P00144642', 'P00201342', 'P00251942', 'P00191442',
       'P00059742', 'P00116842', 'P00015942', 'P00346542', 'P00188742',
       'P00240242', 'P00270542', 'P00057442', 'P00245642', 'P00350442',
       'P00025442', 'P00080342', 'P00246142', 'P00317642', 'P00303842',
       'P00346442', 'P00295942', 'P0099042', 'P00001142', 'P00189842',
       'P00198742', 'P00004242', 'P00173942', 'P00081142', 'P00329542',
       'P00121342', 'P00159542', 'P00115142', 'P00241642', 'P00062842',
       'P00188542', 'P00088242', 'P00127542', 'P00352142', 'P00150942',
       'P00063342', 'P00156742', 'P00193042', 'P00028542', 'P00184442',
       'P00137542', 'P00086042', 'P00057742', 'P00113342', 'P00154742',
       'P00016342', 'P00128242', 'P00345742', 'P00277642', 'P00004842',
       'P00128042', 'P00194642', 'P00149542', 'P00053842', 'P00116142',
       'P00119742', 'P00241242', 'P00100442', 'P00057642', 'P00070042',
       'P00341342', 'P00117342', 'P00090942', 'P00102342', 'P00057542',
       'P00182742', 'P00002142', 'P00127342', 'P00143342', 'P00277542',
       'P00021842', 'P00182242', 'P00050342', 'P0099742', 'P00244042',
       'P00196142', 'P00187442', 'P00128342', 'P00222942', 'P00352842',
       'P00242742', 'P00015642', 'P00313442', 'P00129342', 'P00161242',
       'P00045342', 'P00119642', 'P00114342', 'P00173842', 'P00205942',
       'P00196042', 'P00221442', 'P00201442', 'P00014642', 'P00285642',
       'P00066542', 'P00322942', 'P00282442', 'P00029542', 'P00128142',
       'P00174142', 'P00016842', 'P00223542', 'P00122442', 'P00233442',
       'P00093342', 'P00364442', 'P00346042', 'P00282242', 'P00001042',
       'P00117842', 'P00053042', 'P00320842', 'P00142942', 'P00035342',
       'P00145642', 'P00305042', 'P00342042', 'P00359242', 'P0095842',
       'P00256042', 'P00065242', 'P00153842', 'P00320942', 'P0095542',
       'P00157642', 'P00070342', 'P00136742', 'P00001542', 'P00329942',
       'P00185842', 'P00048042', 'P00146742', 'P00304642', 'P00361942',
       'P00214642', 'P00296042', 'P00359042', 'P00115742', 'P00330342',
       'P00370042', 'P00320742', 'P00169742', 'P00352242', 'P00198242',
       'P00025342', 'P00192242', 'P00249742', 'P00010542', 'P00155242',
       'P00358342', 'P00127742', 'P00254242', 'P00108542', 'P00195042',
       'P00228342', 'P00144042', 'P00043842', 'P00191942', 'P00193642',
       'P00109542', 'P00163442', 'P00196542', 'P00209642', 'P00283142',
       'P00186642', 'P00191342', 'P00015842', 'P00006942', 'P00253142',
       'P00012242', 'P0096842', 'P00223742', 'P00150842', 'P00059642',
       'P00120742', 'P00054242', 'P00136842', 'P00070942', 'P00074642',
       'P00105342', 'P0094342', 'P00284842', 'P0094742', 'P00113842',
       'P00191242', 'P00294442', 'P00220742', 'P00183342', 'P00186542',
       'P00334042', 'P00002242', 'P00041342', 'P00266942', 'P00140442',
       'P00023342', 'P00259842', 'P00217442', 'P00200242', 'P00334642',
       'P00199342', 'P00173042', 'P00178842', 'P00235842', 'P00044242',
       'P00170242', 'P00010942', 'P00247142', 'P00116942', 'P00149442',
       'P00344442', 'P00083342', 'P00163242', 'P00058242', 'P00191642',
       'P00066242', 'P00118642', 'P00251842', 'P00034142', 'P00165642',
       'P00075342', 'P00247942', 'P0096742', 'P00187342', 'P00310842',
       'P00045142', 'P00183642', 'P00234642', 'P00207342', 'P00034242',
       'P00038142', 'P00294142', 'P00053342', 'P00151242', 'P00035042',
       'P00146042', 'P00233142', 'P00170942', 'P00146842', 'P00308242',
       'P00202142', 'P00190842', 'P00342442', 'P00183842', 'P00082742',
       'P00171642', 'P00187042', 'P00242542', 'P00342142', 'P00351242',
       'P00267342', 'P00067842', 'P00138442', 'P00041442', 'P00035942',
       'P00216242', 'P00339842', 'P00176542', 'P00338942', 'P00148542',
       'P00112242', 'P00293842', 'P00061342', 'P00215242', 'P00229642',
       'P00304342', 'P00266742', 'P00126242', 'P00011942', 'P00163742',
       'P00045042', 'P00087142', 'P00219742', 'P00088642', 'P0095442',
       'P00142842', 'P00213042', 'P00290242', 'P00085142', 'P00160642',
       'P00313842', 'P00173742', 'P00202742', 'P00161842', 'P00005942',
       'P00239742', 'P00328942', 'P00217842', 'P00048342', 'P00186342',
       'P00199142', 'P00318642', 'P00084742', 'P00223042', 'P0099842',
       'P00239242', 'P00340342', 'P00342342', 'P00341942', 'P00016442',
       'P00163542', 'P0096042', 'P00186142', 'P00156242', 'P00111642',
       'P00076542', 'P00274842', 'P00217542', 'P00196342', 'P00351642',
       'P00217642', 'P00131442', 'P00000242', 'P00235942', 'P00369942',
       'P00187142', 'P00008042', 'P00363242', 'P00019042', 'P00269342',
       'P00264542', 'P00182942', 'P00241342', 'P00138042', 'P00147142',
       'P00164042', 'P00183742', 'P00025242', 'P00196242', 'P00053442',
       'P00135242', 'P00342242', 'P00159242', 'P00208442', 'P0099942',
       'P00107142', 'P00173142', 'P00136242', 'P00146542', 'P00045242',
       'P00229142', 'P00140542', 'P00356342', 'P00351742', 'P00353342',
       'P00267442', 'P00107042', 'P00353442', 'P00290742', 'P00159742',
       'P00298042', 'P0095042', 'P00337342', 'P00296842', 'P00092842',
       'P00050042', 'P00249442', 'P00358642', 'P00345542', 'P00174642',
       'P00005542', 'P00311742', 'P00247442', 'P00014442', 'P00337242',
       'P00185742', 'P00342542', 'P00239042', 'P00223442', 'P00157442',
       'P00243042', 'P00164442', 'P00076942', 'P00038042', 'P00321242'],
      dtype=object)

In [ ]:
# In this product id there are so many unique values.
# Now I want to see how many unique values present in that column.
# I want to get the count of unique values.
data['Product_ID'].nunique()     #Number of unique values

525

In [ ]:
# Now I want to check how many values are male and how many values are female
data['Gender'].unique()

array(['F', 'M'], dtype=object)

In [ ]:
# Now I want to check how many values are male and how many values are female
data['Gender'].value_counts()

Gender
M    62549
F    18033
Name: count, dtype: int64

In [ ]:
data['Age'].value_counts()

Age
26-35    32313
36-45    15908
18-25    15321
46-50     6365
51-55     5489
55+       2829
0-17      2357
Name: count, dtype: int64

In [ ]:
# In my dataset I observed there are few columns which are of object data type.
# Now I want to convert them into numerical.

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()

In [ ]:
for x in data.columns:
  if data[x].dtype =='object':
    data[x] = le.fit_transform(data[x])

In [ ]:
data

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
1,1000001,391,0,0,10.0,0,2,0.0,1.0,6.0,14.0,15200.0
6,1000004,284,1,4,7.0,1,2,1.0,1.0,8.0,17.0,19215.0
13,1000005,211,1,2,20.0,0,1,1.0,1.0,2.0,5.0,15665.0
14,1000006,363,0,5,9.0,0,1,0.0,5.0,8.0,14.0,5378.0
16,1000006,517,0,5,9.0,0,1,0.0,2.0,3.0,4.0,13055.0
...,...,...,...,...,...,...,...,...,...,...,...,...
262997,1004472,402,0,4,16.0,1,0,1.0,1.0,11.0,16.0,15175.0
263001,1004472,337,0,4,16.0,1,0,1.0,1.0,11.0,15.0,15430.0
263003,1004472,480,0,4,16.0,1,0,1.0,1.0,2.0,15.0,15387.0
263006,1004472,49,0,4,16.0,1,0,1.0,8.0,13.0,16.0,5861.0
263011,1004473,159,1,3,1.0,1,3,0.0,1.0,8.0,17.0,19253.0

# Let's suppose it was observed that the average purchase made by the Men of age group 18-25 was 10000. Is it still the same?

In [ ]:
data['Age'].unique()

array([0, 4, 2, 5, 3, 1, 6])

In [ ]:
# Note down the null and alternate hypothesis
# Create a new or sub dataset based on the conditions.
# Now the new dataset will be my entire population.
# From this population we need to create sample.
# We perform hypothesis testing
# We conclude whether it is null or alternative.

In [ ]:
# Null Hypothesis -> Average purchase made by Men of the age group 18-25 is 10000.
# Alternate Hypothesis -> Average purchase made by Men of the age group 18-25 is not 10000.

In [ ]:
new_data = data.loc[(data['Age']==1) & (data['Gender']==1)]   #age==1 I am selecting all the rows which are of age grop 18-25

In [ ]:
new_data                            #Population

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
98,1000022,487,1,1,15.0,0,4,0.0,1.0,8.0,17.0,12099.0
103,1000022,402,1,1,15.0,0,4,0.0,1.0,11.0,16.0,12098.0
111,1000022,358,1,1,15.0,0,4,0.0,2.0,4.0,15.0,9564.0
127,1000025,332,1,1,4.0,2,4,0.0,1.0,5.0,9.0,15361.0
128,1000025,71,1,1,4.0,2,4,0.0,1.0,2.0,15.0,15770.0
...,...,...,...,...,...,...,...,...,...,...,...,...
262758,1004446,180,1,1,18.0,1,1,1.0,1.0,2.0,15.0,11512.0
262759,1004446,394,1,1,18.0,1,1,1.0,1.0,15.0,18.0,11521.0
262760,1004446,23,1,1,18.0,1,1,1.0,1.0,2.0,13.0,3988.0
262764,1004446,75,1,1,18.0,1,1,1.0,5.0,8.0,17.0,5444.0
262952,1004465,209,1,1,4.0,0,1,1.0,2.0,3.0,4.0,3240.0

In [ ]:
#rule is to take 30 but practically when you will use t-test you will be taking 10 -20 % as sample and performing t-test

In [ ]:
# Whenever in problem statement there is mean or average mentioned we use t-test.
# Whenever there is percentage or preportion mentioned you have to use z-test.

In [ ]:
data.sample(5,random_state=12345)    #sample function is used to generate samples randomly
                                     #random_state is used to lock the pattern of your data.
                    #From 0 till infinite any +ve numeric value you can pass in random_state

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
44634,1000890,158,1,1,4.0,2,4,0.0,1.0,15.0,16.0,15550.0
167718,1001883,188,0,5,0.0,1,1,1.0,5.0,12.0,14.0,3465.0
82542,1000753,0,1,0,10.0,2,1,0.0,3.0,4.0,5.0,13309.0
9231,1001418,304,1,1,4.0,0,1,1.0,1.0,2.0,15.0,11888.0
139035,1003503,382,1,1,4.0,1,0,0.0,1.0,2.0,15.0,11565.0

In [ ]:
sample_size = 1000    # Approx 10% of my data I am selecting as sample out of population.
new_data_sample = new_data.sample(sample_size, random_state=0)
new_data_sample

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
124490,1001221,184,1,1,0.0,1,1,0.0,1.0,2.0,5.0,7943.0
66720,1004217,6,1,1,4.0,1,2,0.0,1.0,5.0,8.0,15811.0
194073,1005964,418,1,1,5.0,1,1,0.0,2.0,3.0,10.0,12882.0
157342,1000302,262,1,1,4.0,1,4,0.0,13.0,15.0,16.0,570.0
199012,1000742,411,1,1,0.0,2,1,0.0,1.0,2.0,15.0,11519.0
...,...,...,...,...,...,...,...,...,...,...,...,...
104629,1004101,186,1,1,4.0,2,3,0.0,1.0,5.0,18.0,12001.0
66214,1004117,355,1,1,4.0,1,4,0.0,1.0,8.0,17.0,11416.0
165259,1001524,455,1,1,4.0,1,1,0.0,2.0,8.0,16.0,16448.0
80254,1000352,181,1,1,4.0,0,0,0.0,1.0,2.0,15.0,11572.0
259306,1003942,271,1,1,4.0,1,4,0.0,1.0,6.0,8.0,11428.0

In [ ]:
from scipy.stats import ttest_1samp     #I am importing one sample ttest from scipy. statistics library

In [ ]:
t_stat, p_value = ttest_1samp(new_data_sample['Purchase'],10000)

In [ ]:
p_value

2.8550147774368676e-26

In [ ]:
if p_value < 0.05:
  print("We have to reject null Hypothesis - Average purchase made by the Men is not 10000")
else:
  print("Failed to reject the null Hypothesis - Average purchase made by Men is 10000")


  # p_value > 0.05 Fail to reject null hypothesis.

We have to reject null Hypothesis - Average purchase made by the Men is not 10000

In [ ]:
data

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
1,1000001,391,0,0,10.0,0,2,0.0,1.0,6.0,14.0,15200.0
6,1000004,284,1,4,7.0,1,2,1.0,1.0,8.0,17.0,19215.0
13,1000005,211,1,2,20.0,0,1,1.0,1.0,2.0,5.0,15665.0
14,1000006,363,0,5,9.0,0,1,0.0,5.0,8.0,14.0,5378.0
16,1000006,517,0,5,9.0,0,1,0.0,2.0,3.0,4.0,13055.0
...,...,...,...,...,...,...,...,...,...,...,...,...
262997,1004472,402,0,4,16.0,1,0,1.0,1.0,11.0,16.0,15175.0
263001,1004472,337,0,4,16.0,1,0,1.0,1.0,11.0,15.0,15430.0
263003,1004472,480,0,4,16.0,1,0,1.0,1.0,2.0,15.0,15387.0
263006,1004472,49,0,4,16.0,1,0,1.0,8.0,13.0,16.0,5861.0
263011,1004473,159,1,3,1.0,1,3,0.0,1.0,8.0,17.0,19253.0

In [ ]:
# Is the percentage of men who have spent more than 10000 the same for the ages 18-25 and 26-35?


# Null hypothesis -> Men who have spent more than 10000 are same for the ages 18-25 and 26-35.
# Alternate hypothesis ->Men who have spent more than 10000 are not same for the ages 18-25 and 26-35.

In [ ]:
df_new = data[data['Purchase']>10000]

In [ ]:
df_new

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
1,1000001,391,0,0,10.0,0,2,0.0,1.0,6.0,14.0,15200.0
6,1000004,284,1,4,7.0,1,2,1.0,1.0,8.0,17.0,19215.0
13,1000005,211,1,2,20.0,0,1,1.0,1.0,2.0,5.0,15665.0
16,1000006,517,0,5,9.0,0,1,0.0,2.0,3.0,4.0,13055.0
18,1000007,58,1,3,1.0,1,1,1.0,1.0,14.0,16.0,11788.0
...,...,...,...,...,...,...,...,...,...,...,...,...
262995,1004472,175,0,4,16.0,1,0,1.0,1.0,11.0,15.0,11661.0
262997,1004472,402,0,4,16.0,1,0,1.0,1.0,11.0,16.0,15175.0
263001,1004472,337,0,4,16.0,1,0,1.0,1.0,11.0,15.0,15430.0
263003,1004472,480,0,4,16.0,1,0,1.0,1.0,2.0,15.0,15387.0
263011,1004473,159,1,3,1.0,1,3,0.0,1.0,8.0,17.0,19253.0

In [ ]:
data_men_1 = df_new.loc[(df_new['Gender']==1) & (df_new['Age']==2)]   # 18-25
data_men_2 = df_new.loc[(df_new['Gender']==1) & (df_new['Age']==3)]   # 26-35

In [ ]:
data_men_1

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
13,1000005,211,1,2,20.0,0,1,1.0,1.0,2.0,5.0,15665.0
19,1000008,393,1,2,12.0,2,4,1.0,1.0,5.0,15.0,19614.0
24,1000008,438,1,2,12.0,2,4,1.0,1.0,8.0,14.0,11927.0
64,1000015,64,1,2,7.0,0,1,0.0,1.0,2.0,6.0,11458.0
198,1000036,479,1,2,3.0,1,0,0.0,1.0,15.0,16.0,15812.0
...,...,...,...,...,...,...,...,...,...,...,...,...
262939,1004461,266,1,2,20.0,2,3,0.0,1.0,2.0,15.0,15285.0
262941,1004461,241,1,2,20.0,2,3,0.0,10.0,15.0,16.0,18764.0
262944,1004461,91,1,2,20.0,2,3,0.0,3.0,4.0,12.0,11071.0
262945,1004461,93,1,2,20.0,2,3,0.0,1.0,2.0,3.0,15474.0
262987,1004471,154,1,2,6.0,0,1,0.0,1.0,6.0,8.0,19660.0

In [ ]:
data_men_2

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
18,1000007,58,1,3,1.0,1,1,1.0,1.0,14.0,16.0,11788.0
112,1000023,419,1,3,0.0,1,3,1.0,1.0,2.0,3.0,15766.0
115,1000023,271,1,3,0.0,1,3,1.0,1.0,6.0,8.0,15354.0
116,1000023,2,1,3,0.0,1,3,1.0,1.0,6.0,16.0,12015.0
117,1000023,426,1,3,0.0,1,3,1.0,1.0,2.0,5.0,15371.0
...,...,...,...,...,...,...,...,...,...,...,...,...
262975,1004470,145,1,3,12.0,2,3,1.0,1.0,2.0,8.0,19421.0
262976,1004470,180,1,3,12.0,2,3,1.0,1.0,2.0,15.0,19089.0
262977,1004470,146,1,3,12.0,2,3,1.0,1.0,2.0,5.0,15378.0
262979,1004470,371,1,3,12.0,2,3,1.0,1.0,15.0,16.0,19232.0
263011,1004473,159,1,3,1.0,1,3,0.0,1.0,8.0,17.0,19253.0

In [ ]:
data_men_1.shape     # 1600

(16017, 12)

In [ ]:
data_men_2.shape     # 700

(7680, 12)

In [ ]:
sample_size = 1100
data_men_sample = data_men_1.sample(sample_size,random_state=500)   # From 0 to infinite any value.
data_men_2_sample = data_men_2.sample(sample_size,random_state=31)

In [ ]:
data_men_sample

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
49839,1001635,502,1,2,0.0,1,1,0.0,1.0,2.0,15.0,15701.0
225389,1004715,332,1,2,2.0,1,3,0.0,1.0,5.0,9.0,11904.0
74196,1005437,273,1,2,11.0,2,4,0.0,1.0,5.0,6.0,15801.0
323,1000053,299,1,2,0.0,1,1,0.0,3.0,4.0,5.0,10766.0
64518,1003885,126,1,2,12.0,1,4,1.0,10.0,14.0,16.0,23110.0
...,...,...,...,...,...,...,...,...,...,...,...,...
34296,1005293,415,1,2,12.0,2,2,0.0,2.0,9.0,15.0,13025.0
65073,1003983,146,1,2,0.0,1,1,0.0,1.0,2.0,5.0,15639.0
42421,1000536,155,1,2,20.0,2,1,0.0,1.0,8.0,17.0,19577.0
74560,1005497,327,1,2,4.0,0,1,1.0,1.0,6.0,8.0,15523.0
48989,1001503,322,1,2,12.0,0,2,0.0,1.0,2.0,11.0,15351.0

In [ ]:
data_men_2_sample

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
1577,1000255,246,1,3,0.0,2,1,1.0,2.0,15.0,16.0,13132.0
226465,1004896,486,1,3,6.0,2,3,1.0,3.0,4.0,5.0,13535.0
87022,1001422,382,1,3,17.0,1,3,0.0,1.0,2.0,15.0,11720.0
141076,1003772,482,1,3,17.0,1,0,1.0,6.0,8.0,15.0,20684.0
220260,1003955,264,1,3,0.0,2,0,1.0,1.0,6.0,14.0,15795.0
...,...,...,...,...,...,...,...,...,...,...,...,...
8672,1001328,138,1,3,14.0,0,1,0.0,1.0,2.0,15.0,15718.0
68479,1004473,174,1,3,1.0,1,3,0.0,1.0,5.0,18.0,15169.0
100711,1003600,274,1,3,20.0,1,4,1.0,1.0,5.0,6.0,15489.0
31451,1004808,376,1,3,0.0,0,1,1.0,1.0,11.0,15.0,11388.0
98725,1003313,489,1,3,20.0,0,2,0.0,1.0,2.0,16.0,11419.0

In [ ]:
from scipy.stats import ttest_ind  #Two tailed independent sample t-test

In [ ]:
t_stat, p_value = ttest_ind(data_men_sample['Purchase'],data_men_2_sample['Purchase'],equal_var=True)
p_value

0.8537904455930129

In [ ]:
if p_value < 0.05:
  print("We have to reject null Hypothesis - Men who have spent more than 10000 are not same for the ages 18-25 and 26-35")
else:
  print("Failed to reject the null Hypothesis - Men who have spent more than 10000 are same for the ages 18-25 and 26-35")

Failed to reject the null Hypothesis - Men who have spent more than 10000 are same for the ages 18-25 and 26-35

# Is the average purchase made by men and women of the age 18-25 is same

In [ ]:
# Null -> Average purchase made by men and women of the age 18-25 is same.
# Alternate -> Average purchase made my men and women of the age 18-25 is not same.

In [ ]:
# what we are comparing  -> Average
# If you see average -> t-test
# I am comparing here two groups
# 2 sample t-test

In [ ]:
data_men = data.loc[(data['Gender']==1) & (data['Age']==1)]
data_women = data.loc[(data['Gender']==0) & (data['Age']==1)]

In [ ]:
data_women

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
71,1000018,300,0,1,3.0,1,3,0.0,3.0,4.0,9.0,10754.0
72,1000018,229,0,1,3.0,1,3,0.0,4.0,8.0,9.0,2802.0
73,1000018,152,0,1,3.0,1,3,0.0,1.0,2.0,5.0,19473.0
75,1000018,51,0,1,3.0,1,3,0.0,1.0,14.0,16.0,19313.0
76,1000018,351,0,1,3.0,1,3,0.0,1.0,2.0,13.0,15182.0
...,...,...,...,...,...,...,...,...,...,...,...,...
262254,1004371,232,0,1,4.0,1,3,0.0,8.0,14.0,16.0,8111.0
262383,1004387,309,0,1,4.0,1,0,0.0,1.0,2.0,9.0,7792.0
262403,1004387,207,0,1,4.0,1,0,0.0,1.0,14.0,16.0,4140.0
262411,1004387,105,0,1,4.0,1,0,0.0,3.0,5.0,16.0,13287.0
262415,1004387,193,0,1,4.0,1,0,0.0,4.0,5.0,13.0,684.0

In [ ]:
data_men.shape   # 1000 approx 10%   Sample size must be same for both the datasets.

(11904, 12)

In [ ]:
data_women.shape   # 300 approx 10%

(3417, 12)

In [ ]:
sample_size = 500   #In between value we will select
data_men_sample = data_men.sample(sample_size,random_state=29)
data_women_sample = data_women.sample(sample_size,random_state=31)

In [ ]:
data_women_sample

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
234851,1000200,393,0,1,4.0,2,0,0.0,1.0,5.0,15.0,15650.0
152729,1005605,260,0,1,2.0,0,0,0.0,2.0,5.0,14.0,3624.0
36366,1005605,153,0,1,2.0,0,0,0.0,1.0,5.0,12.0,4518.0
20959,1003312,513,0,1,4.0,0,3,0.0,3.0,4.0,12.0,8045.0
91946,1002106,32,0,1,20.0,0,3,1.0,5.0,8.0,14.0,3578.0
...,...,...,...,...,...,...,...,...,...,...,...,...
195971,1000242,271,0,1,4.0,0,3,0.0,1.0,6.0,8.0,8326.0
113701,1005547,333,0,1,4.0,0,3,1.0,5.0,8.0,14.0,7092.0
164177,1001356,435,0,1,4.0,1,2,0.0,8.0,13.0,16.0,6175.0
238750,1000855,114,0,1,2.0,0,2,1.0,5.0,8.0,14.0,7141.0
78618,1000092,0,0,1,4.0,1,1,0.0,3.0,4.0,5.0,10738.0

In [ ]:
from scipy.stats import ttest_ind    #two tailed independent t-test

# Whenever we apply two sample t-test we need to consider variance of both the data is equal

In [ ]:
t_stat, p_value = ttest_ind(data_men_sample['Purchase'],data_women_sample['Purchase'],equal_var=True)
p_value

0.04347708342463738

In [ ]:
if p_value < 0.05:
  print("We have to reject null Hypothesis - Average purchase made by the Men and Women is not equal")
else:
  print("Failed to reject the null Hypothesis - Average purchase made by Men and Women is equal")

We have to reject null Hypothesis - Average purchase made by the Men and Women is not equal

In [ ]:
# Mean of Product_category_1, product_category_2 and product_category 3 are same  -> Anova

In [ ]:
#  HOMEWORK
# It was observed that the percentage of women that spend more than 10000 was 35 %. Is it still the same?
# z_test